### ISSUE TITLE
下载完解压失败，求助

### ISSUE THREAD

**Issue by tzhang2014** [9crk/mget#4]
https://depositonce.tu-berlin.de/bitstream/11303/9429/5/HpIRs.zip ，这个连接我用bash mget.sh https://depositonce.tu-berlin.de/bitstream/11303/9429/3/HRIRs.zip 100 HRIRs.zip生成的文件大小比原始文件大很多，并且下载得到的zip文件解压失败，请问下是什么问题，谢谢

**Comment by 9crk** [comment]
@tzhang2014  对方服务器有问题，不支持Range指令。

**Comment by 9crk** [comment]
建议开一个国外的VPS,先下载到VPS （国外下载国外一般都是超级高速的）,然后在国内用mget下载下来。

**Comment by tzhang2014** [comment]
找国外的同学帮忙下载了，多谢
